### ISSUE TITLE
High/medium/low thresholds, clarification and simplification

### ISSUE THREAD

**Issue by harrylandles** [JohnAdders/climate_narrative#102]
From Rebecca Lea,
Consistency of high medium and low thresholds across assets and liabilities – feels like this makes sense for assets given the degree of segmentation the tool goes into, but perhaps for liabilities 10% premium written for ‘high’ is a bit low? 
o	Perhaps using the word ‘significant’ would be more intuitive for the user, but we appreciate that here there is a trade-off between keeping the consistency across the tool / in users’ interpretations.
o	A way around this could be to have a bit of an explanation at the beginning of the tool / as a call out box on how a users’ answers will affect the output of the tool, so that they understand the implications of their responses
o	Is there any difference between the outputs from the user selecting either medium or low? It appears that you don’t get details for either, so maybe the user choice could be binary as the choice between medium and low makes no difference to the output? Equally this might be something which is addressed in future iterations of the tool

**Comment by JohnAdders** [comment]
Threshold for high can be changed, agree that with limited categories 10% is probably too low.

Also agree that additional help text explaining what is going to happen would help.

@benkirl can you suggest some text foe explaining how user's answers will affect the results?

**Comment by harrylandles** [comment]
Text added explaining implications of exposure level selection
