### ISSUE TITLE
Add Executive Summary

### ISSUE THREAD

**Issue by harrylandles** [JohnAdders/climate_narrative#103]
From Charlie Heathcote,
It’s really useful to have all of the information in one place, however the report does feel a little overwhelming and I wonder whether it would be useful to have a standard section at the top of each report with a purpose / “how to approach this report” section? Possible coving key uses of the report as well as a brief overview of structure

**Comment by JohnAdders** [comment]
Standard piece of text for non-sector reports dealing with how to use the report

**Comment by harrylandles** [comment]
executive summary added
