### ISSUE TITLE
Compare impacts of scenarios for the most material elements

### ISSUE THREAD

**Issue by harrylandles** [JohnAdders/climate_narrative#106]
From Charlie Heathcote,
Is there any way of comparing the impacts of the three NGFS scenarios for the most material elements for the user? It might not be worth it, but I wonder whether a fourth report would be useful that just provides a factual view of how the scenarios differ and what the key sectoral drivers are based on the users inputs to the tool?

**Comment by JohnAdders** [comment]
Add text that covers difference between 3 scenarios in sector reports

**Comment by JohnAdders** [comment]
Need text

**Comment by harrylandles** [comment]
where relevant we have addded variables that compare between scenarios and associated narratives
