### ISSUE TITLE
Streamline repetition

### ISSUE THREAD

**Issue by harrylandles** [JohnAdders/climate_narrative#110]
From Jeremy Lawson,
There is a lot of repetition in the reports and if we could find ways to streamline it, that will make it more likely it is read.

**Comment by JohnAdders** [comment]
@benkirl can you identify if there is repitition other that the deliberate repetition?

**Comment by harrylandles** [comment]
Only deliberate repetition remains. The report will not show the repetition that we have in the document as it is for specific scenario and materiality
