### ISSUE TITLE
Clarify appropriate use cases and limitations

### ISSUE THREAD

**Issue by harrylandles** [JohnAdders/climate_narrative#111]
From Jeremy Lawson,
Many users are going to be primarily interested in the report to help them understand the impact of the scenarios for asset prices. But as we have discussed, because there is no baseline derived from a market view of the future, and the scenarios are so stylised, the applicability of the tool to portfolio management is going to be quite limited. Being clear about the appropriate use cases and limitations of the tool are going to be critical to avoid it being misused.

**Comment by JohnAdders** [comment]
@benkirl can you make sure that the text going in the intro has something on appropriate use

**Comment by harrylandles** [comment]
Added limitations and appropriate use cases
