### ISSUE TITLE
Inconsistent image sizing on tool and RTF

### ISSUE THREAD

**Issue by karnan-nar10** [JohnAdders/climate_narrative#120]
a lot of the images have different sizing in both the tool and the RTF. Is there a way to make them more consistent?

**Comment by krzmip** [comment]
Sure we can, but what is consistency in this context. Should all images have equal width?

**Comment by karnan-nar10** [comment]
For the majority of the images yes they should have equal width and height (Height 6cm and Length 14cm)

but the below images should have the following height and width:
- NGFS_scenarios_Framework_Orderly (H: 7cm, W: 7cm)
- NGFS_scenarios_Framework_Disorderly (H: 7cm, W: 7cm)
- NGFS_scenarios_Framework_Hothouse (H: 7cm, W: 7cm)
- Orderly_Scenarios (H: 4cm, W: 16cm)
- Hothouse_Scenarios (H: 4cm, W: 16cm)
- Disorderly_Scenarios (H: 4cm, W: 16cm)
- Cumulative_Energy_Investment_Oil_and_Gas (H: 8.5cm, W: 8cm)
- Primary_Energy_Mix_Oil_and_Gas (H: 8.5cm, W: 7.5cm)
- Emissions_Mix_Construction (H: 7.5cm, W: 7.5cm)
- Electricity_Capacity_Orderly (H: 10.8cm, W: 16cm)
- Electricity_Capacity_Disorderly (H: 10.8cm, W: 16cm)
- Primary_Energy_Orderly_Mining (H: 10.8cm, W: 16cm)
- Primary_Energy_Disorderly_Mining (H: 10.8cm, W: 16cm)
- Primary_Energy_Price_Orderly_Utilities (H: 7.8cm, W: 16cm)
- Primary_Energy_Price_Disorderly_Utilities (H: 7.8cm, W: 16cm)
- Secondary_Energy_Electricity_Orderly_Utilities (H: 10.8cm, W: 16cm)
- Secondary_Energy_Electricity_Disorderly_Utilities (H: 10.8cm, W: 16cm)
- IEA_Net_Zero_2050_Roadmap (H: 10.2cm, W: 12.8cm)
- Thai_Flooding_Consumer_Products (H: 6.3cm, W: 14cm)
- Retail_Sales (H: 9.2cm, W: 13.4cm)
- Water_Stress_Mining (H: 10.4cm, W: 10cm)
- Transportation_Final_Energy_Orderly (H: 10cm, W: 16cm)
- Transportation_Final_Energy_Disorderly (H: 10cm, W: 16cm)
- Primary_Energy_Orderly_Oil_and_Gas (H: 7.8cm, W: 16cm)
- Primary_Energy_Disorderly_Oil_and_Gas (H: 7.8cm, W: 16cm)
- Oil_and_Gas_Orderly_Price (H: 7.8cm, W: 16cm)
- Oil_and_Gas_Disorderly_Price (H: 7.8cm, W: 16cm)
- Air_Temp_Low_Physical (H: 7.8cm, W: 16cm)
- Precipitation_Low_Physical (H: 7.8cm, W: 16cm)
- CO2_emissions_Transportation_Orderly (H: 7.8cm, W: 16cm)
- CO2_emissions_Transportation_Disorderly (H: 7.8cm, W: 16cm)
- CO2_emissions_Residential_vs_Commercial_Orderly (H: 7.8cm, W: 16cm)
- CO2_emissions_Residential_vs_Commercial_Disorderly (H: 7.8cm, W: 16cm)
- River_Flood_Depth_Low_Physical (H: 7.8cm, W: 16cm)
- Transportation_Final_Energy_Freight_Passenger_Orderly (H: 7.8cm, W: 16cm)
- Transportation_Final_Energy_Freight_Passenger_Disorderly (H: 7.8cm, W: 16cm)
- Policy_Cost_Orderly (H: 7.8cm, W: 16cm)
- Policy_Cost_Disorderly (H: 7.8cm, W: 16cm)
- Wildfires_and_Heat_Stress_Low_Physical (H: 7.8cm, W: 16cm)
- Residential_Energy_Price_Orderly (H: 9cm, W: 16cm)
- Residential_Energy_Price_Disorderly (H: 9cm, W: 16cm)
- River_Flood_Land_Low_Physical (H: 7.8cm, W: 16cm)
- River_Flood_Depth_Low_Physical  (H: 7.8cm, W: 16cm)
- Share_of_Renewable_Electricity_Generation_Soverign (H: 7cm, W: 16cm)
- Sovereign_Rating_Scale (H: 9.5cm, 9cm)

**Comment by JohnAdders** [comment]
As a first step the ideal set-up would be that all images have a constant width of say 80%

**Comment by krzmip** [comment]
Updated the pull request so that images which have width <300 pixels are not upscaled. Looks reasonably well
