### ISSUE TITLE
All Sectors option in "Select Sector to Show"

### ISSUE THREAD

**Issue by harrylandles** [JohnAdders/climate_narrative#129]
From Kathrina Maguire,
The only thing that wasn’t immediately obvious to me was what to do if you wanted to download a report that contained all (relevant) sectors for a given scenario. I figured out the way to do this was by selecting the blank option in the “Select the sector to show” drop down box. Perhaps this option should be relabelled “All relevant sectors” instead?

**Comment by krzmip** [comment]
should I similarly change the scenario dropdown from blank to "All scenarios"?

**Comment by harrylandles** [comment]
For a Sector Report yes. For Institutional Report I think no; Selecting blank on the scenario dropdown on institutional report does not show a report (which Im assuming is by design since an all scenarios report would likely be too long here)

**Comment by krzmip** [comment]
OK, so I guess conversely, for a sector report the label should then be blank (not "All scenarios").
