### ISSUE TITLE
Separate report between assets and underwriting

### ISSUE THREAD

**Issue by harrylandles** [JohnAdders/climate_narrative#161]
From Vicky Morley,
It would be useful to separate in the report between categories of assets and underwriting / product (e.g. savings and liabilities).

From Rothesay,
It might make sense to split the sector filter into asset and liability side of the balance sheet.

**Comment by harrylandles** [comment]
If firm type is insurance then add extra level of headings and split assets and liabilities

**Comment by krzmip** [comment]
implemented (in the separate branch, not pushed, waiting for merge of refactor pull request)
