### ISSUE TITLE
Add climate scenario page 

### ISSUE THREAD

**Issue by harrylandles** [JohnAdders/climate_narrative#167]
From Rothesay,
Add climate scenario page - A section of the various assumptions made in each scenario to clearly visualise where carbon prices, oil price, gas price, vehicle sales etc translate in each scenario rather than reading qualitative statements in the main body of the report.

**Comment by harrylandles** [comment]
In sector report where only scenario is selected (no sector selected) - output a report with a description of the relevant scenario only

**Comment by krzmip** [comment]
Prepared (but not pushed yet, waiting for approval of the pending refactor pull request).
