### ISSUE TITLE
Production behaviour with no beta code

### ISSUE THREAD

**Issue by JohnAdders** [JohnAdders/climate_narrative#224]
As we move out of beta into production we need to do a few things to tidy up some of the old experimental code.

The production behaviour that we are currently targeting is that the screen where we have the beta code displays just a next box that is connected to the captcha system and we only move to the next screen if we have happy it is not being abused.

We should also remove traces of the email setup as we are not likely to use this anymore

**Comment by krzmip** [comment]
Fix included in pull request as well as shinyapps https://krzmip.shinyapps.io/climate/
