### ISSUE TITLE
Multi-user performance issues

### ISSUE THREAD

**Issue by JohnAdders** [JohnAdders/climate_narrative#246]
When hosted at shinyio or cgfi multiple users share a single R instance, since R is single threaded if there is a long running task then all users navigations and interactions must wait for the long running task to finish before they can be processed.

Some articles explaining a potential workaround

https://rstudio.github.io/promises/articles/shiny.html

https://www.r-bloggers.com/2020/03/shiny-performance-tuning-with-future-promises-part-1/
https://www.r-bloggers.com/2020/04/shiny-performance-tuning-with-future-promises-the-practice/

**Comment by krzmip** [comment]
It seems the solution does not work on CGFI server. Investigation in progress

**Comment by krzmip** [comment]
Investigation did not result in any meaningful conclusion. However, it turns out that the async functionality works now correctly, for unknown reason. Closing the issue
