### ISSUE TITLE
Product types can be duplicated in table

### ISSUE THREAD

**Issue by JohnAdders** [JohnAdders/climate_narrative#33]
For property in the product table if revenue and non-revenue line is selected then we get 2 entries in the report table.

**Comment by krzmip** [comment]
@JohnAdders 

I think the best solution to the duplicate product in the real estate exposures would be to transpose the table. From my point of view it would make perfect sense:
•	“residential” and “commercial” would be sectors 
•	“revenue generating” and “non revenue generating” would be types of exposure
•	This would ensure unique names within a row (a validation check could be added to ensure this)
•	a final table would have two bullets “revenue generating” and “non revenue generating” under say commercial real estate section. 

Krzysztof

**Comment by JohnAdders** [comment]
OK go ahead and make the change.

**Comment by krzmip** [comment]
My solution is a partial fix only as there are two distinct commercial real estates (Commercial, Land Acquisition Development and Construction). Therefore still it was necessary to modify the identifiers to make them unique.
