### ISSUE TITLE
Fix hardcoding of recatpcha code in UI

### ISSUE THREAD

**Issue by JohnAdders** [JohnAdders/climate_narrative#37]
See tab_auth_ui function

**Comment by krzmip** [comment]
@JohnAdders I looked at the function, but seems you already fixed this

**Comment by krzmip** [comment]
sorry, I looked at wrong place. Will fix it myself

**Comment by JohnAdders** [comment]
I think this will need dynamic ui generation here, so a place holder in the ui for the captcha html and then a server function with visability of the already secrets to inject the html
