### ISSUE TITLE
Pressing cancel to file download leaves modal rendering box displayed

### ISSUE THREAD

**Issue by JohnAdders** [JohnAdders/climate_narrative#47]
If you try and download and rtf and then press cancel to the fiel save dialog then the modal rendering box isn't cleared

**Comment by krzmip** [comment]
I think I am not able to replicate this on my computer (on clicking the button no dialog appears, the file is just downloaded). What browser do you use?

**Comment by JohnAdders** [comment]
Chrome, go to settings search for downloads and set the Ask where to save each file before downloading settings to on

**Comment by JohnAdders** [comment]
This appears to have been fixed, original problem may be related to incorrect version of pandoc installed on one of the servers we are deploying to.

**Comment by JohnAdders** [comment]
Closing as can not reproduce.
