### ISSUE TITLE
Consolidate low and high physical risk narratives

### ISSUE THREAD

**Issue by harrylandles** [JohnAdders/climate_narrative#62]
From Lauren McNicoll,
Physical risk narratives are often the same in both high and low risk scenarios. E.g. the only difference for the Agriculture sector is the size of GDP impact. Perhaps an opportunity to consolidate text and/or emphasise where there are differences?

**Comment by JohnAdders** [comment]
Would need code changes to support a common narrative, how common it this?

**Comment by harrylandles** [comment]
Differences are sufficient, no desire to change current structure
