### ISSUE TITLE
Displaying of Details subsections

### ISSUE THREAD

**Issue by harrylandles** [JohnAdders/climate_narrative#69]
From Lauren McNicoll,
We noticed one inconsistency in presenting the ‘Summary’ and ‘Details’ paragraphs:             
o	With a portfolio composed of exposures in different sectors, the narrative page includes four paragraphs for Metals and Mining
	Metals and Mining — Orderly transition — Summary
	Metals and Mining — Orderly transition — Details
	Metals and Mining — Low physical risk — Summary
	Metals and Mining — Low physical risk — Details
o	If the firm states that its only exposures are in ‘Metals and Mining’, only the below gets displayed. For consistency, ‘Details’ paragraphs could also be included.
	Metals and Mining — Orderly transition — Summary
	Metals and Mining — Low physical risk — Summary
o	This seems to also be the case if low exposure is selected, and it may be useful to footnote that more information is available as otherwise it is hidden from the user

**Comment by JohnAdders** [comment]
This is the intended behaviour
