### ISSUE TITLE
Option to download full set of narratives

### ISSUE THREAD

**Issue by harrylandles** [JohnAdders/climate_narrative#81]
From Elliot Rouse,
I think that it would be a good idea as a full back approach to be able to just download the PDF of the full set of narratives.

It might be the case that even the customers don't have exposures to some sectors they might want to be able to see the full narrative regardless, in order to see what other sectors are doing in the space, Or get more narrative on a sector they are exposed but at a low level.

I could not see this other option inside the tool but please do correct me if I'm wrong.

**Comment by JohnAdders** [comment]
It is available in development mode but I do not think extending the tool to support text browsing is sensible as the point of the tool is to be as simple as possible
