### ISSUE TITLE
Exposure to real estate assets under management asked twice

### ISSUE THREAD

**Issue by harrylandles** [JohnAdders/climate_narrative#88]
From Leo Donnachie,
Why is there a commercial real estate option in first exposures page and then another page to enter exposures split out by commercial/residential real estate?

**Comment by JohnAdders** [comment]
Does seem to still be an issue with asset manager pages

**Comment by krzmip** [comment]
OK, simple to fix. I will remove "commercial real estate" as well as "mortgages" from asset managers corporate exposure (similarly as for banks)
